id: swagger-api

info:
  name: swaggerui
  author: nishant57
  severity: info
  tags: exposure,api,swagger,nishantswagger

requests:
  - method: GET
    path:
      - "{{BaseURL}}/swagger/ui/index"
      - "{{BaseURL}}/dev/swagger/ui/index"
      - "{{BaseURL}}/swagger/index.html"
      - "{{BaseURL}}/swagger-ui.html"
      - "{{BaseURL}}/swagger/swagger-ui.html"
      - "{{BaseURL}}/api/swagger-ui.html"
      - "{{BaseURL}}/api-docs/swagger.yaml"
      - "{{BaseURL}}/swagger.yaml"
      - "{{BaseURL}}/swagger/v1/swagger.yaml"
      - "{{BaseURL}}/api/index.html"
      - "{{BaseURL}}/api/swagger.yaml"
      - "{{BaseURL}}/api/swagger.yml"
      - "{{BaseURL}}/api/swagger/index.html"
      - "{{BaseURL}}/api/swagger/swagger-ui.html"
      - "{{BaseURL}}/api/api-docs/swagger.yaml"
      - "{{BaseURL}}/api/swagger-ui/swagger.yaml"
      - "{{BaseURL}}/api/swagger-ui/api-docs"
      - "{{BaseURL}}/api/swagger"
      - "{{BaseURL}}/api/swagger/static/index.html"
      - "{{BaseURL}}/api/swagger-resources"
      - "{{BaseURL}}/api/swagger-resources/restservices/v2/api-docs"
      - "{{BaseURL}}/api/__swagger__/"
      - "{{BaseURL}}/api/_swagger_/"
      - "{{BaseURL}}/api/spec/swagger.yaml"
      - "{{BaseURL}}/api/swagger/ui/index"
      - "{{BaseURL}}/__swagger__/"
      - "{{BaseURL}}/_swagger_/"
      - "{{BaseURL}}/api/v1/swagger-ui/swagger.yaml"
      - "{{BaseURL}}/swagger-resources/restservices/v2/api-docs"
      - "{{BaseURL}}/api/2/explore/"
      - "{{BaseURL}}/api-docs/swagger.yaml"
      - "{{BaseURL}}/api/explorer/swagger-ui.html"
      - "{{BaseURL}}/api/index.html"
      - "{{BaseURL}}/api/kcdb/swagger-ui/index.html"
      - "{{BaseURL}}/api/package_search/v4/documentation"
      - "{{BaseURL}}/api/static/swagger-ui"
      - "{{BaseURL}}/api/swagger-resources/restservices/v2/api-docs"
      - "{{BaseURL}}/api/swagger/ui"
      - "{{BaseURL}}/api/swagger-ui.html"
      - "{{BaseURL}}/api/swagger/ui/index"
      - "{{BaseURL}}/api/swagger-ui/index.html"
      - "{{BaseURL}}/api/swagger-ui/swagger.yaml"
      - "{{BaseURL}}/api/swagger.yaml"
      - "{{BaseURL}}/api/swagger.yml"
      - "{{BaseURL}}/api/v1"
      - "{{BaseURL}}/api/v1/"
      - "{{BaseURL}}/api/v1/api-docs"
      - "{{BaseURL}}/api/v1/apidocs"
      - "{{BaseURL}}/api/v1/swagger"
      - "{{BaseURL}}/api/v1/swagger/"
      - "{{BaseURL}}/api/v1/swagger-ui"
      - "{{BaseURL}}/api/v1/swagger-ui/"
      - "{{BaseURL}}/api/v1/swagger-ui.html"
      - "{{BaseURL}}/api/v1/swagger-ui/swagger.yaml"
      - "{{BaseURL}}/api/v1/swagger.yaml"
      - "{{BaseURL}}/api/v2"
      - "{{BaseURL}}/api/v2/api-docs"
      - "{{BaseURL}}/api/v2/apidocs"
      - "{{BaseURL}}/api/v2/swagger"
      - "{{BaseURL}}/api/v2/swagger/"
      - "{{BaseURL}}/api/v2/swagger-ui"
      - "{{BaseURL}}/api/v2/swagger-ui/"
      - "{{BaseURL}}/api/v2/swagger-ui.html"
      - "{{BaseURL}}/api/v2/swagger.yaml"
      - "{{BaseURL}}/api/v3"
      - "{{BaseURL}}/api/v3/api-docs"
      - "{{BaseURL}}/api/v3/apidocs"
      - "{{BaseURL}}/api/v3/swagger"
      - "{{BaseURL}}/api/v3/swagger/"
      - "{{BaseURL}}/api/v3/swagger-ui"
      - "{{BaseURL}}/api/v3/swagger-ui/"
      - "{{BaseURL}}/api/v3/swagger-ui.html"
      - "{{BaseURL}}/api/v3/swagger.yaml"
      - "{{BaseURL}}/v1/swagger/ui/index.html"
      - "{{BaseURL}}/v2/swagger/ui/index.html"
      - "{{BaseURL}}/v3/swagger/ui/index.html"
      - "{{BaseURL}}/api/v1/swagger/ui/index.html"
      - "{{BaseURL}}/api/v2/swagger/ui/index.html"
      - "{{BaseURL}}/api/v3/swagger/ui/index.html"
      - "{{BaseURL}}/application"
      - "{{BaseURL}}/backoffice/v1/ui"
      - "{{BaseURL}}/build/reference/web-api/explore"
      - "{{BaseURL}}/core/latest/swagger-ui/index.html"
      - "{{BaseURL}}/csp/gateway/slc/api/swagger-ui.html"
      - "{{BaseURL}}/gen-swagger-docs.sh"
      - "{{BaseURL}}/graphql"
      - "{{BaseURL}}/nonswagger"
      - "{{BaseURL}}/rest/v1"
      - "{{BaseURL}}/rest/v1/swagger"
      - "{{BaseURL}}/service/swagger-ui/index.html"
      - "{{BaseURL}}/static/api/swagger.yaml"
      - "{{BaseURL}}/static/swagger-ui/index.html"
      - "{{BaseURL}}/__swagger__/"
      - "{{BaseURL}}/__swagger__/"
      - "{{BaseURL}}/_swagger_/"
      - "{{BaseURL}}/_swagger_/"
      - "{{BaseURL}}/swagger"
      - "{{BaseURL}}/swagger/"
      - "{{BaseURL}}/swagger/api-docs"
      - "{{BaseURL}}/swagger/index.html"
      - "{{BaseURL}}/swagger-resources"
      - "{{BaseURL}}/swagger-resources/swagger-ui.html"
      - "{{BaseURL}}/swagger.sh"
      - "{{BaseURL}}/swagger/static/index.html"
      - "{{BaseURL}}/swagger/swagger"
      - "{{BaseURL}}/swagger/swagger-ui.htm"
      - "{{BaseURL}}/swagger/swagger-ui.html"
      - "{{BaseURL}}/swagger-ui"
      - "{{BaseURL}}/swagger-ui/"
      - "{{BaseURL}}/swagger/ui"
      - "{{BaseURL}}/swaggerui"
      - "{{BaseURL}}/swagger-ui.html"
      - "{{BaseURL}}/swagger/ui/index"
      - "{{BaseURL}}/swagger-ui/index.html"
      - "{{BaseURL}}/swagger/v1"
      - "{{BaseURL}}/swagger/v1/api-docs"
      - "{{BaseURL}}/swagger/v1/swagger.yaml"
      - "{{BaseURL}}/swagger/v2"
      - "{{BaseURL}}/swagger/v2/api-docs"
      - "{{BaseURL}}/swagger/v2/swagger.yaml"
      - "{{BaseURL}}/swagger.yaml"
      - "{{BaseURL}}/swagger.yml"
      - "{{BaseURL}}/ui"
      - "{{BaseURL}}/v1"
      - "{{BaseURL}}/v1.0"
      - "{{BaseURL}}/v1.1"
      - "{{BaseURL}}/v1/swagger-ui.html"
      - "{{BaseURL}}/v1.x/swagger-ui.html"
      - "{{BaseURL}}/v2"
      - "{{BaseURL}}/v2.0"
      - "{{BaseURL}}/v2/api/swagger-ui.html"
      - "{{BaseURL}}/v3"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "swagger:"
          - "Swagger 2.0"
          - "\"swagger\":"
          - "Swagger UI"
          - "**token**:"
        condition: or

      - type: status
        status:
          - 200
